### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by GaneshKandu** [greenrobotllc/adserver#1]
Hi,

1. What is Current Version of adserver where i can see ?

2. Getting Following Error on master

> app/Http/Controllers/AdInfoController.php

ErrorException in AdInfoController.php line 94: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

> app/Http/Controllers/AdInfoController.php

ErrorException in AdInfoController.php line 94: file_get_contents(https://app.mopub.com/reports/custom/api/download_report?report_key=&amp;api_key=&amp;date=2017-04-15): failed to open stream: HTTP request failed! HTTP/1.0 422 Unprocessable Entity

System
PHP 5.6
Apache/2.2.31 (Unix)

**Comment by andytriboletti** [comment]
1. It is currently unversioned.
2. I have fixed this. That error used to occur when you don't have MoPub credentials filled out. I made MoPub optional just now.

Please let me know if you have any questions.
