### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\PackageManifest' not found

### ISSUE THREAD

**Issue by mephiroth** [greenrobotllc/adserver#3]
when i run php composer.phar install  it shows that as below:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\PackageManifest' not found in /home/work/Code/adserver-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:181
Stack trace:
#0 /home/work/Code/adserver-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(151): Illuminate\Foundation\Application->registerBaseBindings()
#1 /home/work/Code/adserver-master/bootstrap/app.php(15): Illuminate\Foundation\Application->__construct('/home/wor...')
#2 /home/work/Code/adserver-master/artisan(18): require_once('/home/wor...')
#3 {main}
  thrown in /home/work/Code/adserver-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 181
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255

**Comment by andytriboletti** [comment]
When I run this command, I don't get an error:

vagrant@homestead:~/Code/adserver$ php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
The compiled services & packages files have been removed.
> php artisan optimize

I Googled this error and found this possible solution: https://stackoverflow.com/a/30904936

Can you let me know if that works?

**Comment by rafailml** [comment]
What works for me was:
1. Deleting composer.lock and vendor dir
2. composer update --no-scripts

**Comment by andytriboletti** [comment]
@mephiroth Did this fix your issue?

**Comment by andytriboletti** [comment]
There is now a setup.sh script that fixes this problem.
