### ISSUE TITLE
Required PHP version is ^7.1

### ISSUE THREAD

**Issue by rafailml** [greenrobotllc/adserver#4]
On composer install result is:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - doctrine/annotations v1.5.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
    - Installation request for doctrine/annotations v1.5.0 -> satisfiable by doctrine/annotations[v1.5.0].

You have to update readme :)

**Comment by andytriboletti** [comment]
Thank you, I have updated the README.
