### ISSUE TITLE
Can't add AdSense Ad Code

### ISSUE THREAD

**Issue by rafailml** [greenrobotllc/adserver#5]
The error is that zone is empty. But it is not. 
I can't paste exact message because I inserted code manually in database. Now when I click on AdSense Ad Code I'm getting exemption:

in AdsenseController.php (line 62)
--
at HandleExceptions->handleError(8, 'Trying to get property of non-object', 'www/test/adserver/app/Http/Controllers/AdsenseController.php', 62, array('data' => object(Collection), 'zones' => object(Collection), 'adsense_zones' => object(Collection), 'zones_tablename' => 'ad_zones', 'zone_mapping_tablename' => 'ad_zone_mappings', 'value' => object(Adsense), 'key' => 0, 'temp' => null))in AdsenseController.php (line 62)

**Comment by rafailml** [comment]
As I said I can't enter it normally, because of error message that zone is empty. Although zone is not empty, I have two zones in combo.

**Comment by andytriboletti** [comment]
Have you set up the Google Client Config JSON file and tried to refresh in order to pull in the adsense zones?

**Comment by rafailml** [comment]
Do you mean Google API Console JSON?
Yes I have ti.

I deleted my database record and in AdSense Ad Code, I have nothing in Adsense Unit combo. 
But the error message is:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'adsense_zone' cannot be null (SQL: insert into `adsenses` (`name`, `adcode`, `adsense_zone`, `updated_at`, `created_at`) values (My Google Adsense, asdfgasdg add abased fg , , 2017-11-26 09:17:26, 2017-11-26 09:17:26))

**Comment by andytriboletti** [comment]
Sorry about that. I believe you have to click "Refresh Ads" at least once in order to pull down the Adsense zones from Google? I'm not sure since you manually edited the database, and I've only ever used Laravel Migrations to work with the database.

**Comment by andytriboletti** [comment]
rafailml, is it ok to close this ticket? Or is it still a problem?

**Comment by rafailml** [comment]
Yes, close it.
