### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by hprateek43** [greenrobotllc/adserver#8]
Can you give a small walkthrough on how I can actaully get this code running? I compiled everything and followed the instructions. Do I then need to migrate this code into apache webserver html root.

**Comment by spitutz** [comment]
maybe the code support only private server..

**Comment by andytriboletti** [comment]
I recommend Docker - Specifically LaraDock which is in the project as a submodule. I'm no docker expert, however. I think you could set the public folder to your apache web server html root and it should work.

**Comment by hprateek43** [comment]
I would like to contribute to the code specially in packaging it as a docker container and developing support for advanced stacks like kubernetes. Also, we can change the serving technology to nginx to support the high traffic requests an adserver is supposed to encounter. Do let me know if it seems OK to you and what development roadmap you have.

**Comment by andytriboletti** [comment]
Sounds good to me. You can submit a PR for any changes you want to
contribute.
