### ISSUE TITLE
Error after Install Process

### ISSUE THREAD

**Issue by scysys** [greenrobotllc/adserver#9]
![Bildschirmfoto 2019-03-14 um 10 39 41](https://user-images.githubusercontent.com/1695531/54346531-89cb4a80-4645-11e9-9927-bd7908cc2890.png)

![Bildschirmfoto 2019-03-14 um 10 39 50](https://user-images.githubusercontent.com/1695531/54346548-90f25880-4645-11e9-98a5-85ee80c7d1e0.png)

Any suggestions?

**Comment by andytriboletti** [comment]
I think you will have to login and setup your ad code with Adsense and/or Life StreetMedia.  An improvement could be displaying that you don't have any ad units setup yet.

**Comment by andytriboletti** [comment]
Let me know if setting up the ad code once logging in makes this error go away.
